apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicename }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: {{ .Values.service.ports.name}}
      port: {{ .Values.service.ports.port}}
      protocol: TCP
      targetPort: {{ .Values.service.ports.targetport}}