apiVersion: v2
name: podinfo 
description: Helm chart for simple podinfo application
version: 1.0.0
appVersion: "6.6.3" 
dependencies:
  - name: podinfo-redis
    version: 7.0.7
    repository: file:///home/vlkovalev/charts/redis
    condition: podinfo-redis.enabled
