#Количество реплик
replicas: 1
servicename: redis

#ConfigMap
configmap:
 redisconf: |
    maxmemory 64mb
    maxmemory-policy allkeys-lru
    save ""
    appendonly no
useConfigMap: true

#Service
service:
  ports:
   name: redis
   port: 6379
   targetport: redis 

# параметры Docker-образа
image:
  repository: redis
  tag: "7.0.7"

# настройки CPU и RAM
resources:
  limits:
    cpu: 1000m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 32Mi

# настройки Volumes
volumeMountsData:            
  - mountPath: /var/lib/redis
    name: data
volumeMountsConfigMap:
  - mountPath: /redis-master
    name: config
